import { createReadStream, type Stats } from 'node:fs';
import { createHash } from 'node:crypto';
import { stat } from 'node:fs/promises';

export type FileFingerprintSuccessResult = {
  status: 'success';
  data: {
    /**
     * Hexadecimal string representing the unique fingerprint of the file, generated by hashing the content sample and identity data.
     */
    fingerprint: string;
  };
};

export type FileFingerprintErrorResult = {
  status: 'error';
  data: {
    /**
     * Descriptive error message indicating the reason for failure (e.g., "not a file", "failed to read file sample").
     */
    message: string;

    /**
     * Additional context about the error, such as the file path and any relevant error objects, to aid in debugging and error handling.
     */
    context: unknown;
  };
};

/**
 * Generates a unique, stable fingerprint for a file by combining file metadata
 * and a content sample. Designed for high performance and low memory footprint.
 * @returns {Promise<FileFingerprintSuccessResult | FileFingerprintErrorResult>} Result object with the hex fingerprint or error context.
 */
export async function getFileFingerprint({
  filePath,
  hashAlgorithm = 'md5',
  sampleSize = 65535,
  identityData,
}: {
  /**
   * Absolute path to the target file for which the fingerprint should be generated.
   */
  filePath: string;

  /**
   * Node.js crypto algorithm to use for hashing (e.g., 'md5', 'sha256'). Default is 'md5' for speed, but can be configured for stronger hashes if needed.
   */
  hashAlgorithm?: string;

  /**
   * Number of bytes to read from the start of the file for hashing.
   * Default is 65535 (64KB) to balance uniqueness and performance.
   */
  sampleSize?: number;

  /**
   * Additional metadata to include in the hash. Can be a static object or a callback that receives file stats and returns an object.
   */
  identityData?: object | undefined | ((data: { stats: Stats }) => object);
}): Promise<FileFingerprintSuccessResult | FileFingerprintErrorResult> {
  const stats = await stat(filePath);

  if (!stats.isFile()) {
    return {
      status: 'error',
      data: {
        message: 'not a file',
        context: {
          filePath,
        },
      },
    };
  }

  const identityParts = typeof identityData === 'function'
    ? identityData({
      stats,
    })
    : identityData ?? {
      size: stats.size,
      mtime: stats.mtimeMs,
    };

  const hash = createHash(hashAlgorithm);

  const error = await new Promise<
    undefined | FileFingerprintErrorResult
  >((resolve) => {
    const stream = createReadStream(filePath, { start: 0, end: sampleSize });
    stream.on('data', (chunk) => {
      hash.update(chunk);
    });
    stream.on('end', () => resolve(undefined));
    stream.on('error', err => resolve({
      status: 'error',
      data: {
        message: 'failed to read file sample',
        context: {
          filePath,
          err,
        },
      },
    }));
  });

  if (error) {
    return error;
  }

  hash.update(JSON.stringify(identityParts));
  const fingerprint = hash.digest('hex');

  return {
    status: 'success',
    data: {
      fingerprint,
    },
  };
}